#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Oct 20 00:59:09 2018

@author: khanhbui
"""

from darkflow.net.build import TFNet
import cv2
import os

os.chdir('/Users/khanhbui/Desktop/Python/darkflow-master')

options = {"model": "cfg/yolo.cfg", "load": "bin/yolo.weights", "threshold": 0.1, "gpu":1}

tfnet = TFNet(options)

imgcv = cv2.imread("./sample_img/sample_dog.jpg")
result = tfnet.return_predict(imgcv)
print(result)

